stages:
  make_dataset:
    cmd: python -m src.stages.make_dataset --config=params.yaml
    deps:
      - src/stages/make_dataset.py
    outs:
      - data/interim/rent.csv
  build_features:
    cmd: python -m src.stages.build_features --config=params.yaml
    deps:
      - data/interim/rent.csv
      - src/stages/build_features.py
    outs:
      - data/processed/rent.csv
  data_split:
    cmd: python -m src.stages.data_split --config=params.yaml
    deps:
      - data/processed/rent.csv
      - src/stages/data_split.py
    outs:
      - data/processed/train_x_rent.csv
      - data/processed/train_y_rent.csv
      - data/processed/test_x_rent.csv
      - data/processed/test_y_rent.csv
  train:
    cmd: python -m src.stages.train --config=params.yaml
    deps:
      - data/processed/train_x_rent.csv
      - data/processed/train_y_rent.csv
      - src/stages/train.py
    outs:
      - models/pipeline.joblib
  evaluate:
    cmd: python -m src.stages.evaluate --config=params.yaml
    deps:
      - data/processed/test_x_rent.csv
      - data/processed/test_y_rent.csv
      - models/pipeline.joblib
      - src/stages/evaluate.py
    outs:
      - reports/metrics.json
      - reports/figures/actual_vs_predicted.png
  