name: CML & DVC
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      - name: Train model
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cml ci --unshallow
          dvc pull
          pip install -U -r requirements.txt
          dvc repro
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune
          # Metrics
          echo "# Metrics" >> report.md
          dvc metrics diff --show-md main >> report.md

          # Visualize actuals vs predicted
          echo "# Plots" >> report.md
          dvc plots diff \
            --target reports/figures/data_actual_vs_predicted.csv \
            --template scatter \
            -x actual \
            -y predicted \
            --show-vega main > vega.json
          vl2png vega.json -s 1.5 > plot.png
          cml publish --md plot.png >> report.md

          cml send-comment report.md