name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: cml_run
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -U pip
          pip install -U -r requirements.txt
          
          dvc repro

          # Compare metrics to main
          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Visualize actuals vs predicted
          dvc plots diff --show-vega main > vega.json

          dvc push --run-cache
          cml send-comment report.md